import { initCraftCards } from './modules/craft-cards.js';
import { initFloatingCta } from './modules/floating-cta.js';
import { initHeroReveal } from './modules/hero-reveal.js';
import { initMailTyping } from './modules/mail-typing.js';
import { initMenu } from './modules/menu.js';
import { initScrollParallax } from './modules/parallax.js';
import { initScrollReveal } from './modules/scroll-reveal.js';
import { initWordReveal } from './modules/word-reveal.js';

const menuToggle = document.getElementById('menu-toggle');
const menu = document.getElementById('site-menu');
const hero = document.querySelector('.hero');
const heroLead = document.getElementById('hero-lead');
const revealImage = document.getElementById('hero-reveal-image');
const collectionMedia = document.querySelector('.collection__media');
const mailTyped = document.querySelector('.mail-card__typed');
const collectionSection = document.getElementById('collection');
const craftSection = document.getElementById('craft');
const reserveSection = document.getElementById('reserve');
const floatingCta = document.querySelector('.floating-cta');
const craftCards = document.querySelectorAll('[data-craft-card]');
const animatedElements = document.querySelectorAll('.reveal-on-scroll');
const canUseReveal = window.matchMedia('(hover: hover) and (pointer: fine)').matches;
const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

initMenu(menuToggle, menu);
initWordReveal(heroLead, 'hero__word', 2.42);
initMailTyping(mailTyped, reduceMotion);
initScrollParallax(hero, collectionMedia, reduceMotion);
initCraftCards(craftCards);
initFloatingCta(floatingCta, collectionSection, craftSection, reserveSection);
initScrollReveal(animatedElements, reduceMotion);
initHeroReveal(hero, revealImage, canUseReveal, reduceMotion);
